# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-19 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20180919_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('realname', models.CharField(max_length=20)),
                ('add_time', models.IntegerField(default=0)),
                ('disabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('add_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
