# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0002_auto_20180920_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('disabled', models.BooleanField(default=False)),
                ('types', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.types')),
            ],
        ),
        migrations.CreateModel(
            name='goods_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField()),
                ('add_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.members')),
                ('goods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.goods')),
            ],
        ),
        migrations.CreateModel(
            name='goods_introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField(default='')),
                ('add_time', models.DateTimeField()),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xadmin.members')),
                ('goods', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.goods')),
            ],
        ),
    ]
