# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_goods_goods_img_goods_introduce'),
    ]

    operations = [
        migrations.CreateModel(
            name='powers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField(default=0)),
                ('control', models.CharField(max_length=100)),
                ('fun', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='role_power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.powers')),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField()),
            ],
        ),
        # migrations.AddField(
        #     model_name='goods_img',
        #     name='disabled',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='goods_introduce',
        #     name='disabled',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='role_power',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.roles'),
        ),
    ]
