# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0004_auto_20180925_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_img',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goods_introduce',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
