# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0006_members_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powers',
            name='control',
        ),
        migrations.RemoveField(
            model_name='powers',
            name='fun',
        ),
        migrations.AddField(
            model_name='powers',
            name='add_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xadmin.members'),
        ),
        migrations.AddField(
            model_name='powers',
            name='url_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roles',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
