# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
