# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-28 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0009_floor_floor_goods'),
        ('user', '0002_auto_20180919_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xadmin.goods')),
                ('users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
